---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wharf-db-secret
  namespace: wharf
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBv6GfXnojLuoKI5YHpqQqaxT9fcppnnoO2jizEDDUq7RG5sK92OTNl7EqHW8gcrOY+qRVlA9czwpD5pRopV1OOtZcjF5K9pEdfWgFC/dgsfleWq+CUOG8/DFlyx9x805Rj6Re4pzHxMBAxYPXvl65PEO88DIQeU+GewOS+UL2Uge4JtBElJCtu7v3xHUKifacGOgq7x0e+3Y5pvR4xFsxRwN0RyAW56C7IRpSkB57i2+KGIkOe7efpAFMe64dX2nTgYqq9KeHBMUEQ/O5sZqC0fu3v6sGb08Biw68ZG65gzPbb5RDfPXvahOivuhp2uaJk9B+4i8FPBNqsdnFTHETqyjvkyStHWtGShXSQely+hxqewnYf5mbBxHFNNvqXSY8p/35kdRage6Cumsn/WCMGdoh4m78h1f3ZNcwdCZzgFbHRjrJxPeQ16WkuBc24teYC+2sCOPZJoNWaUD6/YThqqYkao1/y9wESdxGmeL35uK0GhTiE/kHCWZrwk6xEO22bDwcZu2C0x++tMov8Xod3WhXAeoPArJSDsbyzt2YuyFv/8qWqm2SEDsVNnDRz8ZQYONElsJcU6CSK+3u8KnVFpp1ZghxbRbnM1Jd/CI/NFG3a1Fn8CcUdfScO7ukUNHr3FUUejoc/qgAI3rZATrrlfmfOkZjlOp2K5cxikXkdemKoUXgvVyTfTKlIqkSu2SPpYZxCrKUbK4JS2KUET2tQNNmHcQc7gIrDUUg+1Parqw==
  template:
    metadata:
      name: wharf-db-secret
      namespace: wharf
