---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wharf-jwt-secret
  namespace: wharf
spec:
  encryptedData:
    JWT_SECRET_KEY: AgAJqzhsLg/UApRSfArtxaG6NKN0LI5VWfKBmlVIqJLXd2mRoM2/L32GKb6ir3HUC9pNOuyPE7EM72GTEFjTL6bzldPbiGl7f7KHrBI2Xd57hosC9Zm/PjnjWI73V6k4cU7sR7dsHCaNtgGv3G6gbIliLgRsoDMvpS8bFmERCLjOs2mZUT9g/RzGzxCfkqO/081n7OHhyT7GHCkyObeGEHoqo6LBT2d6/m56chrxJdH7oph4EWJn/iFKXtWQE40Ly2Sr0lAJ8qRGjUiu3/vogGrNqMAV2iuCvpq9egzVXVA1roltngz2hf173p9U+UIuzYzY41C4+hSFAsphVzu25qaV/M3mn6qp3DpFv58HyIjZyyKyj7qEh+YLaL1NLmjQTcyXkTex8iew5PZXbsvNAC3Cf+UCh93bKfmFWyoN+M6TA5TUkiVGcplBZeOhbEiHlif7hfngKYc1yqC7gcvfdIXvJZ2hNuRw2eTIpXmSAEkEeGKpdCLDIYaUmWCWPJoFBfhkhG0dynsxcag/6D22/ginRGawrjh96fgxPG+S4ZcUP7UWNsEKM7gHSjGsORZUefKEHIvGb3j61ZIbshujCFQesAfo/y9TfgJkSQ6UQAl9N9kDMYrQIpsZ+9QAMs6h52GSMy+SWwKY48uUqtQZ9EY9euDZty06TiRHhQpGqPL86uxIp43Y3ik1WZ1WO1rsO+RcvdgxdFE7XclGjVmRt+JkkHYLHE0PEBZl2PSEjqjFrYj0sgET8W9gfVScZF7mMUZbnaHyE5hljSdoJDO6ej7S
  template:
    metadata:
      name: wharf-jwt-secret
      namespace: wharf
