---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wharf-mail-secret
  namespace: wharf
spec:
  encryptedData:
    MAIL_SERVICE_API_KEY: AgBMRtoBUAoHLHMBsh7d2+D/rzttQvMhKfQfYKO+BweTZBCFHLJjHv6ofpcQpz540mTJFyM/Pi6td46JFXnds/w5lr6aiv9iEmzXc5SZkF/bM6NZN1VQhR8zi4OT4+CKjEqbiAb5wZCmBRDvLSxZItXR/gcb1bMH8m4v75YRoVJvjUEIQH49gx+E6vzBO6MkED+zQxEM8bmURiZvZcxIytdXaI7ODfQl+QdzM3xywhyf26vU41AoKTxhbUSDWHJKWpzWOksBzKbY4yT3VOwilc/1yUwaSwod5fUqKZH38DIguADpPyQgVhRP3n/IE0mJe88Xo1HaVW9ZsvSz1pzsMP3M5ik3PUytlGgGIw8wQlkysCd1EqwKkqQax37Yt4CO6yzuPRY5c9mHPWZL8wp9MWMuoiB3HdUhDtZNwYBiolCTUid5asf+QQo729dpMxUPF/p8S0EKc9BYSscWkVSPewEIyCYmR+NlIHcgbilMhk3RJ10AqXP1yvlwmxLllffyMTvEao9K58BGcAkeqtCvX4mWC7m7xuHu0B89+dpmqaIMrzyKAhRbyooiqZwdSpYOY1Rs1FYHOBR2ijjB/pMAlJcvYWS0Ai3NGxhc+xn/raJpBz2WcZWBmbBDw5G+OrMZXvPxhlW7n5bM2lf1sQ/xuCnZXWH13fcCB274zIn/nnyeNOxltPjPZab75x/gssJ2Qaf63uodIcbaqx5kuFJbC3yjWx5HnHiUeEFaz9iRcfdzIKHs9NTT+LE6yivmF5ocE+aMTQuCazK4BK+QOdbUdF5K7DOwAGfj5KEpknvv7u/kO3X4LQ==
  template:
    metadata:
      name: wharf-mail-secret
      namespace: wharf
